Breadfast/helm-chart

charts/service/templates/cronjob.yaml
=> using dollar-sign instead of dot

charts/service/Chart.yaml, charts/service/README.md
=> update chart version

charts/service/Chart.yaml, charts/service/README.md, charts/service/values.yaml
=> add datadog to default values

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/_helpers.tpl
splitting build number from image tag and set datadog version
=> short version

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml, charts/service/values.yaml
=> Add Node Tolerations

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/cronjob.yaml
=> Add tolerations to cronJob template

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/argoo-rollouts.yaml, charts/service/templates/deployment.yaml, charts/service/templates/service-canary.yaml, charts/service/values.yaml
=>  add argo rollouts

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
=> add rollout to hpa

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
Update the corn template because it's not supported in GKE 1.25+.
=> Update HorizontalPodAutoscaler Version

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
=> Fix sidecars indentation

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
allow services to indicate lifecycle events
=> allow services to indicate lifecycle events

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
=> allow services to indicate lifecycle events - fixed identation

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
allow pods to specify grace period
=> added option for grace period

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
Allow more control on scaling behavior to prevent flapping
=> add option to allow customizing scaling behavior

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
scale down one pod at a time by default
=> on scale down remove a pod at a time

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
By default scale down one pod at a time
=> adjust default scaledown policy

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/hpa.yaml
increase pods by 10% at a time
=> adjust pods increase in scaling out

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
support specifying initContainers
=> add initContainers

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/argoo-rollouts.yaml
Add labels to differentiate between canary and stable in metrics
=> add and stable canary labels

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/argoo-rollouts.yaml
similar to labels, set annotations
=> allow setting deployment annotations on rollout

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml, charts/service/values.yaml
Allow specifying deployment strategy
- [X ] Meaningful PR title
- [ X] Updated README
=> allow specifying deployment rollout strategy

charts/service/README.md, charts/service/templates/service.yaml, charts/service/values.yaml
=> adding additional port to service.yaml

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/service.yaml, charts/service/values.yaml
=> adding enabled value

charts/service/README.md, charts/service/templates/service.yaml, charts/service/values.yaml
=> Update the port name of the extra service

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml
=> Edit linting for goreplay

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/argoo-rollouts.yaml
=> Fix Linting GoReplay

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/deployment.yaml, charts/service/templates/ingress.yaml, charts/service/templates/service.yaml, charts/service/values.yaml
=> Added support to configure multiple ports for service container

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/service.yaml, charts/service/values.yaml
=> Fix an issue in service template when using multiple ports option

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/validate-job.yaml
=> Fix argocd presync validation job command

charts/service/Chart.yaml, charts/service/README.md, charts/service/templates/validate-job.yaml, charts/service/values.yaml
=> Added option to add annotations to the validate job pod
